version: "3"
services: 
  dotnet-api:
    image: sturdy7/dotnet-api:1.0
    ports:
    -  5000:80
    depends_on:
    - mysql
  mysql:
    image: mysql
    ports:
    - 5001:3306
    environment:
    - MYSQL_ROOT_PASSWORD=sturdy