CREATE TABLE `sys`.`Kvp` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `K` VARCHAR(45) NOT NULL,
  `V` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  UNIQUE INDEX `K_UNIQUE` (`K` ASC));
